server:
  port: 8186
  servlet:
    context-path: /market-auth
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/auth
    hikari:
      username: postgres
      password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
jwt:
  secret: e4Tft6a9okn4nECCe34H8LL1KN7IxXFn
  lifetime: 3600000