openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger openApi
  license:
    name: MIT
servers:
  - url: "http://localhost:8188/market-order/api/v1"
paths:
  /orders:
    get:
      summary: Returns a Order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: "#/components/schemas/Order"
  /orders/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: object
      summary: Returns a Order by Id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        address:
          type: string
        phone:
          type: string
        listOrderItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderItems"
    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productTitle:
          type: string
        count:
          type: integer
          format: int32
        pricePerProduct:
          type: integer
          format: int32
        totalPrice:
          type: integer
          format: int32



